FROM nginx:1.16.0-alpine
LABEL maintainer="mayconvm@gmail.com"

COPY infra/templates/nginx/nginx-config.conf /etc/nginx/nginx.conf

COPY infra/templates/nginx/sites-available-default /etc/nginx/conf.d/default.conf

CMD nginx-debug -g 'daemon off;'
